### ISSUE TITLE
[META] Make Jenkins infrastructure setup public

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-ci#2]
The Jenkins instance that runs CI/CD jobs is setup via CDK. There's no reason why that should not be OSS AFAIK so that anyone can deploy a similar instance. 

Work checklist:
- [x] Create base Jenkins CDK codebase
   - [x] #10
   - [x] #12
   - [x] Deploy main jenkins instance
   - [x] Follow security guidance for locking down the instance
   - [x] Add instance health monitoring
   - [x] Create a health dashboard
- [x] Create stack for manual secrets deployment
   - [x] House and deploy certs
   - [x] House and deploy github account credentials
   - [x] https://github.com/opensearch-project/opensearch-ci/issues/23
- [x] Deploy operational instance
   - [x] Install plugins
   - [x] https://github.com/opensearch-project/opensearch-ci/issues/25
   - [x] https://github.com/opensearch-project/opensearch-ci/issues/24
   - [x] #42
- [x] Release Process
  - [x] #43
  - [x] #61
  - [x] #85
  - [x] Config the environment for release to prod
  - [x] Finalize any requirements/features before initial release
- [ ] Post Release
   - [x] #87
   - [ ] Load saved build scripts from DLS
   - [x] Migrate existing configuration
     - [x] https://github.com/opensearch-project/opensearch-ci/issues/38
   - [x] Validate deployment
   - [ ] Job Canary
   
Open questions:
- How can we make sure that we can recover from a down jenkins main node?

**Comment by peternied** [comment]
Major headway on this issue with https://github.com/opensearch-project/opensearch-ci/pull/26 getting merged

**Comment by dblock** [comment]
This can now be closed, right?

**Comment by gaiksaya** [comment]
Jenkins is public. Access it here: https://build.ci.opensearch.org/
