### ISSUE TITLE
[META] Design and deploy ECR cdk stack to deploy repositories and roles related to it.

### ISSUE THREAD

**Issue by abhinavGupta16** [opensearch-project/opensearch-ci#65]
@abhinavGupta16 commented on [Thu Feb 03 2022](https://github.com/opensearch-project/opensearch-build/issues/1592)

## Description
We are able to deploy the ECR related roles and repositories on Isengard using cdk automatically.
The ecr roles set up trust relationships with existing roles/nodes deployed with jenkins-ci

## Tasks
- [x] #67
- [x] https://github.com/opensearch-project/opensearch-ci/issues/52
- [ ] #81

## Acceptance Criteria
- [x] ecr repositories and roles are automatically deployed and setup using cdk
- [x] roles trust relationships are automatically managed with the nodes deployed by jenkins-ci

---

@abhinavGupta16 commented on [Fri Feb 11 2022](https://github.com/opensearch-project/opensearch-build/issues/1592#issuecomment-1036749008)

Following on offline team discussion, we will add the cdk to deploy ECR as a part of `opensearch-ci` . Moving therefore, moving this issue to `opensearch-ci`

**Comment by prudhvigodithi** [comment]
Its better we separate out the ECR creation from [opensearch-ci](https://github.com/opensearch-project/opensearch-ci) repo, as we dont want to recreate/destroy ECR every time Jenkins code is modified. Since creation of ECR is also one time, we can isolate the code with CDK or boto3 to call out the ECR creation and the required roles.

**Comment by prudhvigodithi** [comment]
Recent PR's 
https://github.com/opensearch-project/opensearch-ci/pull/115
https://github.com/opensearch-project/opensearch-build/pull/2128 should support 
Should support ECR related roles as part of CDK
